language: python
python:
  - "3.5"
  # matplotlib requires python-tk
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-tk
  - sudo apt-get install -y python3-tk
install:
  - pip install -r requirements.txt
  - pip install matplotlib
script:
  - py.test
