language: python
python:
  - "3.2"
install:
  - pip install -r requirements.txt
# matplotlib requires python-tk
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-tk
  - sudo apt-get install -y python3-tk
script:
  - py.test
